name: IBM Cloud Foundry - Xray - us-south

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 128M

on:
  workflow_dispatch:
  #repository_dispatch:
  schedule:
    - cron: 42 21 * * 6

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME }}
      Xray_UUID: ${{ secrets.Xray_UUID }}
      Xray_WS_PATH_VMESS: ${{ secrets.Xray_WS_PATH_VMESS }}
      Xray_WS_PATH_VLESS: ${{ secrets.Xray_WS_PATH_VLESS }}

    steps:

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zxC /tmp
        sudo install -m 755 /tmp/cf7 /usr/local/bin/cf
        cf version

    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${IBM_CF_API}" \
          -u "${IBM_CF_USERNAME}" \
          -p "${IBM_CF_PASSWORD}" \
          -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
          -s "${IBM_CF_SPACE_NAME:-dev}"

    - name: Download Latest Xray
      run: |
        DOWNLOAD_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "Xray-linux-64.zip"
        unzip Xray-linux-64.zip
        rm Xray-linux-64.zip
        chmod -v 755 xray
        ./xray version
        mv xray ${IBM_CF_APP_NAME}

    - name: Generate Xray Config File (VMess)
      if: ${{ env.Xray_WS_PATH_VMESS }}
      run: |
        base64 << EOF > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "dns": {
            "servers": [
              {
                "address": "https+local://1.0.0.1/dns-query",
                "port": 443
              }
            ]
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${Xray_UUID}",
                    "alterId": 0
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${Xray_WS_PATH_VMESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {
                "domainStrategy": "UseIP"
              }
            }
          ]
        }
        EOF

    - name: Generate Xray Config File (VLESS)
      if: ${{ env.Xray_WS_PATH_VLESS }}
      run: |
        base64 << EOF > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "dns": {
            "servers": [
              {
                "address": "https+local://1.0.0.1/dns-query",
                "port": 443
              }
            ]
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vless",
              "settings": {
                "decryption": "none",
                "clients": [
                  {
                    "id": "${Xray_UUID}"
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${Xray_WS_PATH_VLESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {
                "domainStrategy": "UseIP"
              }
            }
          ]
        }
        EOF

    - name: Generate Manifest File
      run: |
        cat << EOF > manifest.yml
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          random-route: true
          command: base64 -d config > config.json; ./${IBM_CF_APP_NAME} run -c config.json
          buildpacks:
          - binary_buildpack
        EOF

    - name: Deploy Cloud Foundry App
      run: cf push
